### ISSUE TITLE
Удаление учебного курса не работает

### ISSUE THREAD

**Issue by arykovsb** [NevinLV/djangoCS#1]

**Comment by NevinLV** [comment]
Добавлено удаление курсов. Как и в случае с редактированием, удаление курса доступно только автору или администратору.

![изображение](https://user-images.githubusercontent.com/32606109/150656632-27f11571-b68a-4149-b67c-fcbaf9e4894d.png)

Перед удалением будет предупреждение
![изображение](https://user-images.githubusercontent.com/32606109/150656637-adcc0dc5-f0a4-447e-8319-310045294d96.png)

Для примера оставил на сайте курс, который могут удалить все:
![изображение](https://user-images.githubusercontent.com/32606109/150656688-20b5a65a-5b76-4413-83cf-d7f792fc7337.png)
