### ISSUE TITLE
Редактирование учебного курса

### ISSUE THREAD

**Issue by arykovsb** [NevinLV/djangoCS#2]
Нужна возможность отредактировать название курса, его описание и список тегов.

**Comment by NevinLV** [comment]
Была добавлена возможность редактировать курсы. Редактировать курсы могут только их авторы:
![изображение](https://user-images.githubusercontent.com/32606109/150399544-9ef42780-3283-41bb-ab80-75c7537fe34c.png)
В случае, если другой пользователь каким-то образом попадёт на страницу редактирования курса, то он будет перенаправлен на страницу ошибки доступа. Администратор может редактировать любые курсы.

Выбирается курс, который можно редактировать, и по нажатию на иконку карандаша выполняется переход на страницу редактирования:
![изображение](https://user-images.githubusercontent.com/32606109/150400222-565192ab-6672-4f4d-bb8c-53d6ded90114.png)

![изображение](https://user-images.githubusercontent.com/32606109/150400468-2a92924c-232a-4fa9-98e8-60a029ec3dbf.png)

Выполняются необходимые изменения:
![изображение](https://user-images.githubusercontent.com/32606109/150400720-359fecdf-30bf-43fe-8e36-195720004a72.png)

и при нажатии на кнопку "Изменить" курс редактируется:
![изображение](https://user-images.githubusercontent.com/32606109/150400899-38e36e6e-e3a0-477a-ac00-4e44e5936304.png)

Если изменения не требуются, то можно нажать на кнопку отмены.
