### ISSUE TITLE
Кнопка "Записаться" не работает

### ISSUE THREAD

**Issue by arykovsb** [NevinLV/djangoCS#3]
Как я понял, при нажатии на кнопку должно увеличиваться число в правом нижем углу рядом с иконкой группы. Но этого не происходит.

**Comment by NevinLV** [comment]
Кнопка записи на курс теперь работает. Так же была добавлена кнопка отписки от курса. В зависимости от статуса подписки пользователя на курс меняется кнопка и изменяется количество пользователей, подписанных на курс:

![изображение](https://user-images.githubusercontent.com/32606109/150577597-23f882e3-bb8f-417a-8de2-e50ffb83a656.png)
![изображение](https://user-images.githubusercontent.com/32606109/150577639-e4d3bcff-6a80-4807-8526-877516f342fd.png)
