### ISSUE TITLE
Поиск работает некорректно

### ISSUE THREAD

**Issue by arykovsb** [NevinLV/djangoCS#4]
Нажимаю линк "Найти курс", далее указываю тег и жму кнопку "Поиск". Находятся все курсы. А должны находиться только курсы с указанным тегом.

**Comment by NevinLV** [comment]
**Поиск по тегам исправлен.**

![изображение](https://user-images.githubusercontent.com/32606109/150486595-385d4dc4-46e0-43df-b99b-1c6e336db397.png)

![изображение](https://user-images.githubusercontent.com/32606109/150486617-18898f6f-7a4b-419b-a5ef-67b811dc9c7d.png)

**Comment by arykovsb** [comment]
По тегам поиск действительно работает теперь. Зато по всем остальным полям (название, категория, описание, автор) он работать перестал (который по ссылке НАЙТИ КУРС; а тот поиск, что справа от лого работает исправно по всем полям).

Также уплыла вёрстка:
![img4](https://user-images.githubusercontent.com/97334787/150634776-fb8c1c4e-d964-42f3-8166-1da835a3fa1f.jpg)

**Comment by NevinLV** [comment]
Поиск и вёрстка исправлены
![изображение](https://user-images.githubusercontent.com/32606109/150635857-c91009e5-1c8b-42b6-b136-f5d7982063bc.png)
![изображение](https://user-images.githubusercontent.com/32606109/150635867-1c372073-5e6a-49eb-a75c-9e6b321b1211.png)

**Comment by arykovsb** [comment]
Да, теперь все ОК
