### ISSUE TITLE
Познакомиться с Bootstrap 5

### ISSUE THREAD

**Issue by arykovsb** [NevinLV/djangoCS#8]
[Задание](https://wiki.iaud.ru/doku.php?id=kb:curriculum:web_dev_2#bootstrap)

**Comment by NevinLV** [comment]
Интерфейс был переведён на бутстрап.


- **Формы авторизации и регистрации адаптируются:**

![изображение](https://user-images.githubusercontent.com/32606109/154859473-2e7c8dcb-4171-436f-9629-39c3939a5865.png)
![изображение](https://user-images.githubusercontent.com/32606109/154859483-bce77f54-df18-40db-b738-b88f6be03da9.png)



- **Так же теперь неавторизированные пользователи тоже могут просматривать сайт с https://course-space.herokuapp.com/main:**

![изображение](https://user-images.githubusercontent.com/32606109/154860311-1a7a796c-3a16-4213-87cd-5b7046772406.png)
_Создавать или подписываться на курсы они не могут_



- **Боковое меню при адаптации переходит вниз. Быстрый поиск и кнопка создания курса при адаптации сворачиваются с помощью navbar бутстрапа. Карточки курсов тоже меняются по достижению контрольной точки md:**

![изображение](https://user-images.githubusercontent.com/32606109/154859531-d77af123-7afe-4a0b-b78a-c212f8d0a625.png)
![изображение](https://user-images.githubusercontent.com/32606109/154859553-042da44e-ad08-413c-9866-c3a768eb91cf.png)

- **Все формы адаптируются:**

![изображение](https://user-images.githubusercontent.com/32606109/154859573-1a2fc8df-9044-48d7-b7a5-757ecfe95310.png)
![изображение](https://user-images.githubusercontent.com/32606109/154859583-b46481bf-02dd-4168-97d5-66a942dbae3a.png)

![изображение](https://user-images.githubusercontent.com/32606109/154859596-91d37074-f5e7-4914-8b80-6f409f8dfb73.png)
![изображение](https://user-images.githubusercontent.com/32606109/154859607-9f76d953-053f-4bb4-833b-37ed895c8fd1.png)



- **Сообщение об удалении курса выполнено через диалоговые окна бутстрапа:**

![изображение](https://user-images.githubusercontent.com/32606109/154859625-34f90298-c37a-45b9-af86-04115c724b7c.png)


- **Так же поработал с django и добавил информацию об авторстве и подписках на курсы в профиль:**

![изображение](https://user-images.githubusercontent.com/32606109/154859665-f5ebc348-4115-41a1-b20b-ad12004857f0.png)
![изображение](https://user-images.githubusercontent.com/32606109/154859681-6d3d85fb-1df5-48c5-8e59-65f78bd99e3b.png)



- **Также появилась возможность попасть на страницу профиля автора курса:**

![изображение](https://user-images.githubusercontent.com/32606109/154859697-a96d8224-6169-4777-b091-21922ee8ff41.png)



- +Была добавлена главная страница с отображением всех категорий, топ авторов (по суммарному количеству подписок на их курсы) и топ курсов (по количеству участников)

С адаптацией лендинга пока проблема - почему то, если устройство имеет сенсорное управление, то страница перестаёт адаптироваться. Возможно проблема в каких-то старых стилях.

**Comment by NevinLV** [comment]
Время сложно посчитать для этой задачи. Некоторые элементы дизайна приходилось перепридумывать с учётом адаптации + болел на неделе, очень растянуто получилось, отсюда и много времени заняло. С самим бутстрапом работать легко и быстро.
